# Generated by Django 2.2.6 on 2019-11-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroundStationAntenna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groundStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.GroundStation')),
            ],
        ),
    ]
