# Generated by Django 2.2.6 on 2019-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundstationantenna',
            name='baseBand',
            field=models.CharField(default='unbekannt', max_length=200),
        ),
    ]
