# Generated by Django 2.2.6 on 2019-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0002_groundstationantenna_baseband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundstation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='groundstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='groundstation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='groundstationantenna',
            name='altitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundstationantenna',
            name='latitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundstationantenna',
            name='longitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
