# Generated by Django 2.2.6 on 2019-12-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0003_auto_20191201_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundstation',
            name='altitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundstation',
            name='latitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundstation',
            name='longitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
