# Generated by Django 2.2.6 on 2020-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0004_auto_20191201_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SANA_aperture_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=200)),
                ('OID', models.CharField(max_length=200)),
                ('Frequency_Band', models.CharField(max_length=200)),
                ('Link_Type', models.CharField(max_length=200)),
                ('EIRP', models.CharField(max_length=200)),
                ('G_T', models.CharField(max_length=200)),
                ('Max_Data_Rate', models.CharField(max_length=200)),
                ('Polarization', models.CharField(max_length=200)),
                ('Frequencies', models.CharField(max_length=200)),
                ('Notes', models.CharField(max_length=200)),
                ('References', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('Creation_Date', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('Update_Date', models.CharField(max_length=200)),
            ],
        ),
    ]
