# Generated by Django 2.2.6 on 2020-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0005_sana_aperture_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Creation_Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='EIRP',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Frequencies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Frequency_Band',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='G_T',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Link_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Max_Data_Rate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='OID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Polarization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='References',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='Update_Date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='updated_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
