# Generated by Django 2.2.6 on 2020-02-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0007_sana_aperture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sana_aperture',
            old_name='Pointing_Contraints',
            new_name='Pointing_Constraints',
        ),
    ]
