# Generated by Django 2.2.6 on 2020-02-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0010_sana_aperture_links_aperture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sana_aperture_links',
            name='is_forward_link',
            field=models.BooleanField(null=True),
        ),
    ]
