# Generated by Django 2.2.6 on 2020-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0012_remove_sana_aperture_links_is_forward_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sana_aperture',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sana_aperture_links',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sana_service_sites_apertures',
            name='id',
        ),
        migrations.AlterField(
            model_name='sana_aperture',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sana_service_sites_apertures',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
