# Generated by Django 2.2.6 on 2020-02-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0013_auto_20200203_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='sana_aperture',
            name='service_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.SANA_service_sites_apertures'),
        ),
    ]
