# Generated by Django 2.2.6 on 2020-02-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0014_sana_aperture_service_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='groundstation_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDentification', models.CharField(max_length=200, null=True)),
                ('Ground_Station', models.CharField(max_length=200, null=True)),
                ('Antenna', models.CharField(max_length=200, null=True)),
                ('Owner', models.CharField(max_length=200, null=True)),
                ('Operator', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Latitude', models.CharField(max_length=200, null=True)),
                ('Longitude', models.CharField(max_length=200, null=True)),
                ('Altitude', models.CharField(max_length=200, null=True)),
                ('Orbit_Support', models.CharField(max_length=200, null=True)),
                ('Mount', models.CharField(max_length=200, null=True)),
                ('Full_Motion_LEOP', models.CharField(max_length=200, null=True)),
                ('Diameter', models.CharField(max_length=200, null=True)),
                ('Baseband', models.CharField(max_length=200, null=True)),
                ('SLE_Provider', models.CharField(max_length=200, null=True)),
                ('Baseband_Combiner', models.CharField(max_length=200, null=True)),
                ('Band', models.CharField(max_length=200, null=True)),
                ('Beam_width_degrees', models.CharField(max_length=200, null=True)),
                ('Uplink_Frequency_MHz', models.CharField(max_length=200, null=True)),
                ('Downlink_Frequency_MHz', models.CharField(max_length=200, null=True)),
                ('Polarisation', models.CharField(max_length=200, null=True)),
                ('EIRP_dBW', models.CharField(max_length=200, null=True)),
                ('G_T_dBW_kg', models.CharField(max_length=200, null=True)),
                ('Additional_Info_for_G_T', models.CharField(max_length=200, null=True)),
                ('Angle_Data', models.CharField(max_length=200, null=True)),
                ('Doppler', models.CharField(max_length=200, null=True)),
                ('Tracking_Modes', models.CharField(max_length=200, null=True)),
                ('Tracking_Combiner', models.CharField(max_length=200, null=True)),
                ('Access_Node', models.CharField(max_length=200, null=True)),
                ('Ground_Link_Bandwidth', models.CharField(max_length=200, null=True)),
                ('Remarks', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
