# Generated by Django 2.2.6 on 2020-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0015_auto_20200203_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundstation_excel',
            old_name='G_T_dBW_kg',
            new_name='G_T_dBW_K',
        ),
        migrations.AddField(
            model_name='groundstation_excel',
            name='Slew_Track',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groundstation_excel',
            name='Tracking_Accuracy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groundstation_excel',
            name='Visibility_GEO',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
