# Generated by Django 2.2.6 on 2020-02-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0016_auto_20200211_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groundstation_excel',
            new_name='ge',
        ),
    ]
