# Generated by Django 2.2.6 on 2020-02-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0018_sa'),
    ]

    operations = [
        migrations.CreateModel(
            name='sssa',
            fields=[
                ('Status', models.CharField(max_length=200, null=True)),
                ('OID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Abbreviation', models.CharField(max_length=200, null=True)),
                ('Owner', models.CharField(max_length=200, null=True)),
                ('Operator', models.CharField(max_length=200, null=True)),
                ('Network_Name', models.CharField(max_length=200, null=True)),
                ('Location_Type', models.CharField(max_length=200, null=True)),
                ('Planetary_Body', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=200, null=True)),
                ('State_Region', models.CharField(max_length=200, null=True)),
                ('Latitude', models.CharField(max_length=200, null=True)),
                ('Longitude', models.CharField(max_length=200, null=True)),
                ('Elevation', models.CharField(max_length=200, null=True)),
                ('Operating_Domain', models.CharField(max_length=200, null=True)),
                ('Trajectory', models.CharField(max_length=200, null=True)),
                ('PoC', models.CharField(max_length=200, null=True)),
                ('Requestor', models.CharField(max_length=200, null=True)),
                ('Affiliation', models.CharField(max_length=200, null=True)),
                ('Site_Service_Info', models.CharField(max_length=200, null=True)),
                ('Apertures', models.CharField(max_length=200, null=True)),
                ('Notes', models.CharField(max_length=200, null=True)),
                ('References', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('Creation_Date', models.CharField(max_length=200, null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('Update_Date', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sal',
            fields=[
                ('Status', models.CharField(max_length=200, null=True)),
                ('OID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Frequency_Band', models.CharField(max_length=200, null=True)),
                ('Link_Type', models.CharField(max_length=200, null=True)),
                ('EIRP', models.CharField(max_length=200, null=True)),
                ('G_T', models.CharField(max_length=200, null=True)),
                ('Max_Data_Rate', models.CharField(max_length=200, null=True)),
                ('Polarization', models.CharField(max_length=200, null=True)),
                ('Frequencies', models.CharField(max_length=200, null=True)),
                ('Notes', models.CharField(max_length=200, null=True)),
                ('References', models.CharField(max_length=200, null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('Creation_Date', models.CharField(max_length=200, null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('Update_Date', models.CharField(max_length=200, null=True)),
                ('aperture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.SANA_aperture')),
            ],
        ),
    ]
