# Generated by Django 2.2.6 on 2020-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0019_sal_sssa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sana_aperture',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
