# Generated by Django 2.2.6 on 2020-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0020_auto_20200211_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sal',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sana_aperture_links',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
