# Generated by Django 2.2.6 on 2020-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0021_auto_20200211_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sssa',
            name='OID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
