# Generated by Django 2.2.6 on 2020-02-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0022_auto_20200211_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sa',
        ),
    ]
