# Generated by Django 2.2.6 on 2020-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0023_delete_sa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ge',
            name='alt',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ge',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ge',
            name='lon',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
    ]
