# Generated by Django 2.2.6 on 2020-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0024_auto_20200211_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ge',
            name='uplink_frequency_max',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ge',
            name='uplink_frequency_min',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
