# Generated by Django 2.2.6 on 2020-02-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0027_ge_diameter_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundstation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='groundstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='groundstation',
            name='longitude',
        ),
    ]
