# Generated by Django 2.2.6 on 2020-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0028_auto_20200212_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='ge',
            name='erip_max_dBW_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ge',
            name='erip_min_dBW_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
