# Generated by Django 2.2.6 on 2020-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0032_ge_groundstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sana_aperture',
            name='alt',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='diameter_m',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='downlink_frequency_max_MHz',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='downlink_frequency_min_MHz',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='eirp_max_dbw',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='eirp_min_dbw',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='gsname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='gt_max_dbw_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='gt_min_dbw_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='lon',
            field=models.DecimalField(decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='uplink_frequency_max_MHz',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sana_aperture',
            name='uplink_frequency_min_MHz',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
