# Generated by Django 2.2.6 on 2020-02-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0033_auto_20200213_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStationAperture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('altitude', models.CharField(max_length=200)),
                ('groundStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.GroundStation')),
            ],
        ),
        migrations.CreateModel(
            name='GroundStationApertureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_donwlink', models.BooleanField()),
                ('is_uplink', models.BooleanField()),
                ('f_min', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('f_max', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('EIRP_min', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('EIRP_max', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('G_T_min', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('G_T_max', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('groundStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.GroundStationAperture')),
            ],
        ),
    ]
