# Generated by Django 2.2.6 on 2020-02-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0034_groundstationaperture_groundstationaperturelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sana_aperture',
            name='downlink_frequency_max_MHz',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='downlink_frequency_min_MHz',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='eirp_max_dbw',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='eirp_min_dbw',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='gt_max_dbw_k',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='gt_min_dbw_k',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='uplink_frequency_max_MHz',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='uplink_frequency_min_MHz',
        ),
    ]
