# Generated by Django 2.2.6 on 2020-02-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0035_auto_20200213_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='excelaperture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('lat', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('lon', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('alt', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('groundstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbitscalc.GroundStation')),
            ],
        ),
        migrations.CreateModel(
            name='excel_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('lon', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('alt', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('frequency_min_MHz', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('frequency_max_MHz', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('eirp_min_dbw', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('eirp_max_dbw', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gt_min_dbw_k', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gt_max_dbw_k', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('is_downlink', models.BooleanField()),
                ('groundstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.GroundStation')),
            ],
        ),
        migrations.AddField(
            model_name='ge',
            name='aperture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbitscalc.excelaperture'),
        ),
    ]
