# Generated by Django 2.2.6 on 2020-02-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0036_auto_20200214_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_link',
            name='groundstation',
        ),
        migrations.AddField(
            model_name='excel_link',
            name='aperture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbitscalc.excelaperture'),
        ),
    ]
