# Generated by Django 2.2.6 on 2020-02-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0037_auto_20200214_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_link',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='excel_link',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='excel_link',
            name='lon',
        ),
    ]
