# Generated by Django 2.2.6 on 2020-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0038_auto_20200214_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_link',
            name='eirp_max_dbw',
        ),
        migrations.RemoveField(
            model_name='excel_link',
            name='eirp_min_dbw',
        ),
        migrations.RemoveField(
            model_name='excel_link',
            name='gt_max_dbw_k',
        ),
        migrations.RemoveField(
            model_name='excel_link',
            name='gt_min_dbw_k',
        ),
        migrations.AddField(
            model_name='excelaperture',
            name='eirp_max_dbw',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excelaperture',
            name='eirp_min_dbw',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excelaperture',
            name='gt_max_dbw_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excelaperture',
            name='gt_min_dbw_k',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
