# Generated by Django 2.2.6 on 2020-03-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0039_auto_20200214_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_link',
            name='aperture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orbitscalc.excelaperture'),
        ),
    ]
