# Generated by Django 2.2.6 on 2020-03-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0041_excelaperture_verwendbar'),
    ]

    operations = [
        migrations.RenameModel('sssa', 'sana_groundstation')
    ]
