# Generated by Django 2.2.6 on 2020-03-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0042_auto_20200330_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundstation',
            name='operator',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
