# Generated by Django 2.2.6 on 2020-03-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0043_groundstation_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelaperture',
            name='verwendbar',
        ),
    ]
