# Generated by Django 2.2.6 on 2020-03-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0048_auto_20200330_1456'),
    ]

    operations = [
        migrations.DeleteModel('GroundStationAperture'),
    ]
