# Generated by Django 2.2.6 on 2020-03-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0051_remove_groundstationantenna_groundstation'),
    ]

    operations = [
        migrations.DeleteModel('GroundStationAntenna'),
    ]
