# Generated by Django 2.2.6 on 2020-03-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0052_auto_20200330_1500'),
    ]

    operations = [
        migrations.RenameModel('ge', 'excel_data')
    ]
