# Generated by Django 2.2.6 on 2020-03-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0053_auto_20200330_1505'),
    ]

    operations = [
        migrations.RenameModel('excel_link', 'Link')
    ]
