# Generated by Django 2.2.6 on 2020-03-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0054_auto_20200330_1506'),
    ]

    operations = [
        migrations.RenameModel('excelaperture', 'Aperture'),
    ]
