# Generated by Django 2.2.6 on 2020-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0055_auto_20200330_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='groundstation',
            name='operator',
        ),
        migrations.AlterField(
            model_name='link',
            name='is_downlink',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='groundstation',
            name='operator',
            field=models.ManyToManyField(null=True, to='orbitscalc.Operator'),
        ),
    ]
