# Generated by Django 2.2.6 on 2020-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0056_auto_20200609_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundstation',
            name='operator',
            field=models.ManyToManyField(to='orbitscalc.Operator'),
        ),
    ]
