# Generated by Django 3.0.8 on 2020-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0057_auto_20200609_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='ist_betriebsfaehig',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='aperture',
            name='polarisation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
