# Generated by Django 3.0.8 on 2020-08-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0060_auto_20200830_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperture',
            name='eirp_min_dbw',
        ),
        migrations.RemoveField(
            model_name='aperture',
            name='gt_min_dbw_k',
        ),
    ]
