# Generated by Django 3.0.8 on 2020-08-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0061_auto_20200830_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='lat',
            new_name='latitude',
        ),
    ]
