# Generated by Django 3.0.8 on 2020-08-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0062_auto_20200830_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='lon',
            new_name='longitude',
        ),
    ]
