# Generated by Django 3.0.8 on 2020-08-30 16:51
from django.db import migrations

class Migration(migrations.Migration):
    # Bezug auf vorhergehende Migration
    dependencies = [
        ('orbitscalc', '0063_auto_20200830_1851'),
    ]
    # Aenderungen
    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='alt',
            new_name='altitude',
        ),
    ]
