# Generated by Django 3.0.8 on 2020-12-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0064_auto_20200830_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperture',
            old_name='durchmesser',
            new_name='diameter',
        ),
        migrations.RenameField(
            model_name='aperture',
            old_name='ist_betriebsfaehig',
            new_name='is_operational',
        ),
    ]
