# Generated by Django 3.0.8 on 2020-12-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0065_auto_20201217_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Satellite',
        ),
    ]
