# Generated by Django 3.0.8 on 2020-12-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbitscalc', '0066_delete_satellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_data',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='excel_data',
            name='groundstation',
        ),
        migrations.RemoveField(
            model_name='sal',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='sana_aperture',
            name='service_site',
        ),
        migrations.RemoveField(
            model_name='sana_aperture_links',
            name='aperture',
        ),
        migrations.DeleteModel(
            name='sana_groundstation',
        ),
        migrations.DeleteModel(
            name='excel_data',
        ),
        migrations.DeleteModel(
            name='sal',
        ),
        migrations.DeleteModel(
            name='SANA_aperture',
        ),
        migrations.DeleteModel(
            name='SANA_aperture_links',
        ),
        migrations.DeleteModel(
            name='SANA_service_sites_apertures',
        ),
    ]
